#===============================================================================
# <MODEL_NAME> SITUATION CONFIGURATIONS
#===============================================================================

#===============================================================================
# IRSG PGM METHOD
#===============================================================================
POSTEST_PGM_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data'
  #
  image_dir : './data/<MODEL_NAME>/'
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullpos/'
  imageset_file : '<TRAIN_IMG_FNAMES>_test.txt'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_postest_pgm_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_postest_pgm_{}.csv'

HARDNEG_PGM_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_hardneg/'
  image_dir : './data/LeadingHorseHardNegative/'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_hardneg_pgm_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_hardneg_pgm_{}.csv'

FULLNEG_PGM_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullneg/'
  image_dir : './images/Negatives'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_fullneg_pgm_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_fullneg_pgm_{}.csv'



POSTEST_PGM_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : './data/<MODEL_NAME>/'
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullpos/'
  imageset_file : '<TRAIN_IMG_FNAMES>_test.txt'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_postest_pgm/'
  viz_file_format : '{}.jpg'

HARDNEG_PGM_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_hardneg/'
  image_dir : './data/LeadingHorseHardNegative/'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_hardneg_pgm/'
  viz_file_format : '{}.jpg'

FULLNEG_PGM_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullneg/'
  image_dir : './images/Negatives'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_fullneg_pgm/'
  viz_file_format : '{}.jpg'



#===============================================================================
# GEOMETRIC MEAN METHOD
#===============================================================================

POSTEST_GEO_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : './data/<MODEL_NAME>/'
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullpos/'
  imageset_file : '<TRAIN_IMG_FNAMES>_test.txt'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_postest_geo_energy.csv'

HARDNEG_GEO_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_hardneg/'
  image_dir : './data/LeadingHorseHardNegative/'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_hardneg_geo_energy.csv'

FULLNEG_GEO_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullneg/'
  image_dir : './images/Negatives'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_fullneg_geo_energy.csv'



POSTEST_GEO_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : './data/<MODEL_NAME>/'
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullpos/'
  imageset_file : '<TRAIN_IMG_FNAMES>_test.txt'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_postest_geo/'
  viz_file_format : '{}.jpg'

HARDNEG_GEO_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_hardneg/'
  image_dir : './data/LeadingHorseHardNegative/'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_hardneg_geo/'
  viz_file_format : '{}.jpg'

FULLNEG_GEO_VIZ:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullneg/'
  image_dir : './images/Negatives'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'geo_mean'
  viz_output_dir : './output/full_runs/<MODEL_NAME>/viz_fullneg_geo/'
  viz_file_format : '{}.jpg'



#===============================================================================
# BRUTE FORCE METHOD
#===============================================================================
POSTEST_BF_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data'
  #
  image_dir : './data/<MODEL_NAME>/'
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullpos/'
  imageset_file : '<TRAIN_IMG_FNAMES>_test.txt'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'brute'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_postest_brute_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_postest_brute_{}.csv'

HARDNEG_BF_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_hardneg/'
  image_dir : './data/LeadingHorseHardNegative/'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'brute'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_hardneg_brute_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_hardneg_brute_{}.csv'

FULLNEG_BF_ENERGY:
  query_string : '<QUERY_STR>'
  query_function : '<QUERY_FN>'
  #
  gmm_filename : '<MODEL_SHORT_NAME>_gmms.pkl'
  data_dir : './data/'
  #
  precalc_dir : './run_results/<MODEL_SHORT_NAME>_fullneg/'
  image_dir : './images/Negatives'
  class_file : './data/<MODEL_NAME>_classes.txt'
  #
  energy_method : 'brute'
  energy_output_dir : './output/full_runs/<MODEL_NAME>/'
  energy_filename : '<MODEL_SHORT_NAME>_fullneg_brute_energy.csv'
  top_rel_filefmt : '<MODEL_SHORT_NAME>_fullneg_brute_{}.csv'