#===============================================================================
# Person Has Beard SITUATION CONFIGURATIONS
#===============================================================================

#===============================================================================
# IRSG PGM METHOD
#===============================================================================

TEST_PGM_ENERGY:
  query_string : 'person has beard'
  query_function : 'sro'
  #
  gmm_filename : 'minivg_gmms.pkl'
  data_dir : './data'
  #
  image_dir : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/PersonHasBeardTrain'
  precalc_dir : '/home/econser/research/irsg_psu_pdx/run_results/minivg_PersonHasBeard'
  imageset_file : '/home/econser/research/irsg_psu_pdx/minivg_queries/PersonHasBeardTrainSet.txt'
  class_file : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/minivg_classes.txt'
  #
  energy_output_dir : '/home/econser/research/irsg_psu_pdx/output/full_runs/mvg_PersonHasBeard/pgm_energy'
  energy_filename : 'MVG_PHB_pgm_energy.csv'
  top_rel_filefmt : 'MVG_PHB_pgm_{}.csv'

TEST_PGM_VIZ:
  query_string : 'person has beard'
  query_function : 'sro'
  #
  gmm_filename : 'minivg_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/PersonHasBeardTrain'
  precalc_dir : '/home/econser/research/irsg_psu_pdx/run_results/minivg_PersonHasBeard'
  imageset_file : '/home/econser/research/irsg_psu_pdx/minivg_queries/PersonHasBeardTrainSet.txt'
  class_file : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/minivg_classes.txt'
  #
  viz_output_dir : '/home/econser/research/irsg_psu_pdx/output/full_runs/mvg_PersonHasBeard/pgm_viz'
  viz_file_format : '{}.jpg'



#===============================================================================
# GEOMETRIC MEAN METHOD
#===============================================================================

TEST_GEO_ENERGY:
  query_string : 'person has beard'
  query_function : 'sro'
  #
  gmm_filename : 'minivg_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/PersonHasBeardTrain'
  precalc_dir : '/home/econser/research/irsg_psu_pdx/run_results/minivg_PersonHasBeard'
  imageset_file : '/home/econser/research/irsg_psu_pdx/minivg_queries/PersonHasBeardTrainSet.txt'
  class_file : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/minivg_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/irsg_psu_pdx/output/full_runs/mvg_PersonHasBeard/geo_energy'
  energy_filename : 'MVG_PHB_geo_energy.csv'

TEST_GEO_VIZ:
  query_string : 'person has beard'
  query_function : 'sro'
  #
  gmm_filename : 'minivg_gmms.pkl'
  data_dir : './data/'
  #
  image_dir : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/PersonHasBeardTrain'
  precalc_dir : '/home/econser/research/irsg_psu_pdx/run_results/minivg_PersonHasBeard'
  imageset_file : '/home/econser/research/irsg_psu_pdx/minivg_queries/PersonHasBeardTrainSet.txt'
  class_file : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/minivg_classes.txt'
  #
  energy_method : 'geo_mean'
  viz_output_dir : '/home/econser/research/irsg_psu_pdx/output/full_runs/mvg_PersonHasBeard/geo_viz'
  viz_file_format : '{}.jpg'



#===============================================================================
# BBOX GENERATION CONFIGS
#===============================================================================

GEN_BBOXES:
  data_dir : './data/'
  image_dir : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/PersonHasBeardTrain'
  model_file : '/home/econser/research/irsg_psu_pdx/models/model_definitions/mini_vg'
  weights : '/home/econser/research/irsg_psu_pdx/models/model_weights'
  class_file : '/home/econser/research/irsg_psu_pdx/data/minivg_queries/minivg_classes.txt'
  box_and_score_output_dir : '/home/econser/research/irsg_psu_pdx/run_results/minivg_PersonHasBeard'