#===============================================================================
# query_string : query as a string
# query_function : function to convert query string to mat_struct
#
# data_dir : directory for finding GMMs
# gmm_filename : GMM pkl file
#
# precalc_dir : root dir for precalculated data
#
# image_dir : directory for input images
# model_file : fq path for caffe model
# weights : fq path for model weights
# class_file : classes in the model
#===============================================================================

#===============================================================================
# DOG WALKING CONFIGS (BOXES ONLY)
#===============================================================================

DW_FULLPOS:
  data_dir : './data/'
  image_dir : './images/psu_dw/PortlandSimpleDogWalking/'
  model_file : './models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : './data/dog_walking_classes.txt'
  box_and_score_output_dir : './run_results/dw_fullpos/'

DW_ORIGNEG:
  data_dir : './data/'
  image_dir : './images/psu_dw/orig_negatives/'
  model_file : './models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : './data/dog_walking_classes.txt'
  box_and_score_output_dir : './run_results/dw_origneg/'

DW_HARDNEG:
  data_dir : './data/'
  image_dir : './images/DogWalkingHardNeg/'
  model_file : './models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : './data/dog_walking_classes.txt'
  box_and_score_output_dir : './run_results/dw_hardneg/'

DW_FULLNEG:
  data_dir : './data/'
  image_dir : './images/Negatives'
  model_file : './models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : './data/dog_walking_classes.txt'
  box_and_score_output_dir : './run_results/dw_fullneg/'



#===============================================================================
# STANFORD CONFIGS (BOXES ONLY)
#===============================================================================

STAN_DW_FULLPOS:
  data_dir : './data/'
  image_dir : './images/StanfordSimpleDogWalking/'
  model_file : './models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : './data/dog_walking_classes.txt'
  box_and_score_output_dir : './run_results/stanford_dog_walking/'



#===============================================================================
# PING PONG CONFIGS (BOXES ONLY)
#===============================================================================
PP_POS:
  data_dir : './data/'
  image_dir : './data/PingPong/'
  model_file : './models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : './data/pingpong_classes.txt'
  box_and_score_output_dir : './run_results/pingpong/'

PP_FULLNEG:
  data_dir : './data/'
  image_dir : './images/Negatives'
  model_file : './models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : './data/pingpong_classes.txt'
  box_and_score_output_dir : './run_results/pingpong_fullneg/'

PP_HARDNEG:
  data_dir : './data/'
  image_dir : './images/PingPongHardNeg'
  model_file : './models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : './data/pingpong_classes.txt'
  box_and_score_output_dir : './run_results/pingpong_hardneg/'



#===============================================================================
# HANDSHAKE (BOXES ONLY)
#===============================================================================

HS_FULLPOS:
  data_dir : './data/'
  image_dir : './data/Handshake/'
  model_file : './models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/handshake_50k.caffemodel'
  class_file : './data/handshake_classes.txt'
  box_and_score_output_dir : './run_results/hs_fullpos/'

HS_HARDNEG:
  data_dir : './data/'
  image_dir : './images/HandshakeHardNeg/'
  model_file : './models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/handshake_50k.caffemodel'
  class_file : './data/handshake_classes.txt'
  box_and_score_output_dir : './run_results/hs_hardneg/'

HS_FULLNEG:
  data_dir : './data/'
  image_dir : './images/Negatives'
  model_file : './models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : './models/model_weights/handshake_50k.caffemodel'
  class_file : './data/handshake_classes.txt'
  box_and_score_output_dir : './run_results/hs_fullneg/'



#===============================================================================
# LEADING HORSE (BOXES ONLY)
#===============================================================================

LH_FULLPOS:
  data_dir : './data/'
  image_dir : './data/LeadingHorse/'
  model_file : '/home/econser/research/irsg_psu_pdx/models/model_definitions/leadinghorse/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/irsg_psu_pdx/models/model_weights/leadinghorse_50k.caffemodel'
  class_file : 'leadinghorse_classes.txt'
  box_and_score_output_dir : './run_results/lh_fullpos/'

LH_HARDNEG:
  data_dir : './data/'
  image_dir : './data/LeadingHorseHardNegative/'
  model_file : '/home/econser/research/irsg_psu_pdx/models/model_definitions/leadinghorse/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/irsg_psu_pdx/models/model_weights/leadinghorse_50k.caffemodel'
  class_file : 'leadinghorse_classes.txt'
  box_and_score_output_dir : './run_results/lh_hardneg/'

LH_FULLNEG:
  data_dir : './data/'
  image_dir : './images/Negatives'
  model_file : '/home/econser/research/irsg_psu_pdx/models/model_definitions/leadinghorse/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/irsg_psu_pdx/models/model_weights/leadinghorse_50k.caffemodel'
  class_file : 'leadinghorse_classes.txt'
  box_and_score_output_dir : './run_results/lh_fullneg/'