#===============================================================================
# query_string : query as a string
# query_function : function to convert query string to mat_struct
#
# data_dir : directory for finding GMMs
# gmm_filename : GMM pkl file
#
# precalc_dir : root dir for precalculated data
#
# image_dir : directory for input images
# model_file : fq path for caffe model
# weights : fq path for model weights
# class_file : classes in the model
#===============================================================================

#===============================================================================
# DOG WALKING CONFIGS (GENERATE BOXES AND RUN BATCH)
#===============================================================================

DW_FULLPOS:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  image_dir : '/home/econser/research/images/psu_dw/PortlandSimpleDogWalking/'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/dw_fullpos/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_chain_fullpos_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dw_cycle_fullpos_viz'
  viz_file_format : 'viz_{}.jpg'

DW_ORIGNEG:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  image_dir : '/home/econser/research/images/psu_dw/orig_negatives/'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/dw_origneg/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_cycle_origneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dw_cycle_origneg_viz'
  viz_file_format : 'viz_{}.jpg'

DW_HARDNEG:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  image_dir : '/home/econser/research/images/DogWalkingHardNeg/'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/dw_hardneg/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_cycle_hardneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dw_cycle_hardneg_viz'
  viz_file_format : 'viz_{}.jpg'

DW_FULLNEG:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  image_dir : '/home/econser/research/images/Negatives'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/dw_fullneg/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_cycle_fullneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dw_cycle_fullneg_viz'
  viz_file_format : 'viz_{}.jpg'



#===============================================================================
# DOG WALKING CONFIGS (RUN BATCH)
#===============================================================================

DW_FULLPOS_BATCHONLY:
  #query_string : 'dog_walker holding leash attached_to dog'
  #query_function : 'two_rel_chain'
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  image_dir : '/home/econser/research/images/psu_dw/PortlandSimpleDogWalking/'
  precalc_dir : '/home/econser/research/run_results/dw_fullpos/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_chain_fullpos_energy.csv'
  #viz_output_dir : '/home/econser/research/output/situations/dw_cycle_fullpos_viz'
  #viz_file_format : 'viz_{}.jpg'

DW_ORIGNEG_BATCHONLY:
  #query_string : 'dog_walker holding leash attached_to dog'
  #query_function : 'two_rel_chain'
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_origneg/'
  image_dir : '/home/econser/research/images/psu_dw/orig_negatives/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_chain_origneg_energy.csv'
  #viz_output_dir : '/home/econser/research/output/situations/dw_cycle_origneg_viz'
  #viz_file_format : 'viz_{}.jpg'

DW_HARDNEG_BATCHONLY:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_hardneg/'
  image_dir : '/home/econser/research/images/DogWalkingHardNeg/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_cycle_hardneg_energy.csv'
  #viz_output_dir : '/home/econser/research/output/situations/dw_cycle_hardneg_viz'
  #viz_file_format : 'viz_{}.jpg'

DW_FULLNEG_BATCHONLY:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_fullneg/'
  image_dir : '/home/econser/research/images/Negatives'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dw_cycle_fullneg_energy.csv'
  #viz_output_dir : '/home/econser/research/output/situations/dw_cycle_fullneg_viz'
  #viz_file_format : 'viz_{}.jpg'



#===============================================================================
# DOG WALKING CONFIGS (GEOMETRIC MEAN)
#===============================================================================

DW_FULLPOS_GEOMEAN:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_fullpos/'
  image_dir : '/home/econser/research/images/psu_dw/PortlandSimpleDogWalking/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_dw_cycle_fullpos_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_dw_cycle_fullpos_viz'
  viz_file_format : 'viz_{}.jpg'

DW_HARDNEG_GEOMEAN:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_hardneg/'
  image_dir : '/home/econser/research/images/DogWalkingHardNeg/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_dw_cycle_hardneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_dw_cycle_hardneg_viz'
  viz_file_format : 'viz_{}.jpg'

DW_FULLNEG_GEOMEAN:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  #
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/dw_fullneg/'
  image_dir : '/home/econser/research/images/Negatives'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_dw_cycle_fullneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_dw_cycle_fullneg_viz'
  viz_file_format : 'viz_{}.jpg'



#===============================================================================
# PING PONG CONFIGS
#===============================================================================
PP_POS:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #imageset_file: 'pingpongtest_fnames_test.txt'
  #
  image_dir : '/home/econser/research/data/PingPong/'
  model_file : '/home/econser/research/models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/pingpong/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'pingpong_test_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/pingpong_viz/'
  viz_file_format : 'viz_{}.jpg'

PP_FULLNEG:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #imageset_file: 'pingpongtest_fnames_test.txt'
  #
  image_dir : '/home/econser/research/images/Negatives'
  model_file : '/home/econser/research/models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/pingpong_fullneg/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'pingpong_fullneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/pingpong_fullneg_viz/'
  viz_file_format : 'viz_{}.jpg'

PP_HARDNEG:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #imageset_file: 'pingpongtest_fnames_test.txt'
  #
  image_dir : '/home/econser/research/images/PingPongHardNeg'
  model_file : '/home/econser/research/models/model_definitions/pingpong/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/pingpong_frcn_50k.caffemodel'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  box_and_score_output_dir : '/home/econser/research/run_results/pingpong_hardneg/'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'pingpong_hardneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/pingpong_hardneg_viz/'
  viz_file_format : 'viz_{}.jpg'



#===============================================================================
PP_POS_GEOMEAN:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/pingpong/'
  image_dir : '/home/econser/research/data/PingPong/'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_pingpong_test_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_pingpong_viz/'
  viz_file_format : 'viz_{}.jpg'

PP_FULLNEG_GEOMEAN:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/pingpong_fullneg/'
  image_dir : '/home/econser/research/images/Negatives'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_pingpong_fullneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_pingpong_fullneg_viz/'
  viz_file_format : 'viz_{}.jpg'

PP_HARDNEG_GEOMEAN:
  query_string : 'player, player, table, net; 0 playing_pingpong_with 1, 0 at 2, 1 at 2, 3 on 2'
  query_function : 'split_spec'
  #
  gmm_filename : 'pingpong_gmms.pkl'
  data_dir : '/home/econser/research/data/'
  #
  precalc_dir : '/home/econser/research/run_results/pingpong_hardneg/'
  image_dir : '/home/econser/research/images/PingPongHardNeg'
  class_file : '/home/econser/research/data/pingpong_classes.txt'
  #
  energy_method : 'geo_mean'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'geomean_pingpong_hardneg_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/geomean_pingpong_hardneg_viz/'
  viz_file_format : 'viz_{}.jpg'



#===============================================================================
# HANDSHAKE (BOXES ONLY)
#===============================================================================

HS_FULLPOS:
  data_dir : '/home/econser/research/data/'
  image_dir : '/home/econser/research/data/Handshake/'
  model_file : '/home/econser/research/models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/handshake_50k.caffemodel'
  class_file : '/home/econser/research/data/handshake_classes.txt'
  box_and_score_output_dir : '/home/econser/research/run_results/hs_fullpos/'

HS_HARDNEG:
  data_dir : '/home/econser/research/data/'
  image_dir : '/home/econser/research/images/HandshakeHardNeg/'
  model_file : '/home/econser/research/models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/handshake_50k.caffemodel'
  class_file : '/home/econser/research/data/handshake_classes.txt'
  box_and_score_output_dir : '/home/econser/research/run_results/hs_hardneg/'

HS_FULLNEG:
  data_dir : '/home/econser/research/data/'
  image_dir : '/home/econser/research/images/Negatives'
  model_file : '/home/econser/research/models/model_definitions/handshake/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/handshake_50k.caffemodel'
  class_file : '/home/econser/research/data/handshake_classes.txt'
  box_and_score_output_dir : '/home/econser/research/run_results/hs_fullneg/'



#===============================================================================
# VARIOUS EXAMPLES
#===============================================================================

#-------------------------------------------------------------------------------
# dog walking
#
# precalculated boxes
# energy, viz
#
DW_PREGEN:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  precalc_dir : '/home/econser/research/run_results/dogwalking, positive, portland test/'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  #
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dwhl_energy.csv'
  image_dir : '/home/econser/research/images/psu_dw/PortlandSimpleDogWalking/'
  viz_output_dir : '/home/econser/research/output/situations/dwhl_viz'
  viz_file_format : 'viz_{}.jpg'


#-------------------------------------------------------------------------------
# Dog Walking
#
# 
#
DW_IMAGE_DIR:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  image_dir : '/home/econser/research/images/psu_dw/PortlandSimpleDogWalking'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dwhl_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dwhl_viz'
  viz_file_format : 'viz_{}.jpg'


#-------------------------------------------------------------------------------
# Dog Walking on mini set of images
DW_IMAGE_MINIDIR:
  query_string : 'dog_walker holding leash attached_to dog walked_by dog_walker'
  query_function : 'two_rel_loop'
  gmm_filename : 'dw_gmms_revised.pkl'
  data_dir : '/home/econser/research/data/'
  image_dir : '/home/econser/research/images/psu_dw/dog_walking_mini/'
  model_file : '/home/econser/research/models/model_definitions/dog_walking/faster_rcnn_end2end/test.prototxt'
  weights : '/home/econser/research/models/model_weights/dog_walking_faster_rcnn_final.caffemodel'
  class_file : '/home/econser/research/data/dog_walking_classes.txt'
  energy_output_dir : '/home/econser/research/output/situations/'
  energy_filename : 'dwhl_energy.csv'
  viz_output_dir : '/home/econser/research/output/situations/dwhl_viz'
  viz_file_format : 'viz_{}.jpg'